{{- $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation-msg" )) }}

{{- if .Values.enabled }}
{{- if (eq .Values.cloudProvider "gke") }}
{{ template "pega.gke.backendConfig" dict "node" .Values "name" $depName }}
{{ end }}
{{ end }}