{{- $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation-messaging" )) }}
{{- $requestPath := printf "%s/ping" .Values.urlPath }}

{{- if .Values.enabled }}
{{- if (eq .Values.provider "gke") }}
{{ template "backingservices.gke.backendConfig" dict "root" .Values "name" $depName "requestPath" $requestPath }}
{{ end }}
{{ end }}