apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: constellation
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: constellation
          servicePort: 3000
