#Deploy only when the constellation flag has been enabled in the values yaml.
{{ if and .Values.enabled (eq .Values.enabled true) }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: constellation
  labels:
    app: constellation
    # component: constellation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: constellation
      # component: constellation
  template:
    metadata:
      labels:
        app: constellation
        # component: constellation
    spec:
      imagePullSecrets:
      - name: {{ template "pegaRegistrySecret" }}
      containers:
      - name: constellation
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        args:
        - port=3000
        - sync=true
        - {{ .Values.logLevel }}
        livenessProbe:
          httpGet:
            path: /c11n/api/v1/ping
        ports:
        - containerPort: 3000
{{ end }}
