#Deploy only when the constellation flag has been enabled in the values yaml.
{{ if and .Values.enabled (eq .Values.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: constellation
  labels:
    app: constellation
    # component: constellation
spec:
  selector:
    # is this on the pod or the deployment?
    app: constellation
    # component: constellation
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
  #externalIPs:
  #  - 3.216.78.82
{{ end }}
