#Deploy only when the cosmosUI flag has been enabled in the values yaml.
{{ if and .Values.enabled (eq .Values.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: cosmosUI
  labels:
    app: cosmosUI
    # component: cosmosUI
spec:
  selector:
    app: cosmosUI
    # component: cosmosUI
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
{{ end }}
