apiVersion: v1
kind: Service
metadata:
  name: constellation
  labels:
    app: constellation
spec:
  selector:
    # is this on the pod or the deployment?
    app: constellation
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
  #externalIPs:
  #  - 3.216.78.82
