language: python
env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.11.0-linux-amd64.tar.gz
    - YAMLLINT_VERSION=1.15.0
install:
  # Install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
script:
  - curl -o index.yaml https://stwhitewalkers.bintray.com/pega-helm-charts/index.yaml
  - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
  - helm dep update ./charts/pega/
  - helm package ./charts/pega/
  - helm repo index --merge index.yaml --url https://dl.bintray.com/pegasystems/pega-helm-charts/ .
deploy:
- provider: bintray
  file: descriptor.json
  user: scrumteamwhitewalkers
  key:
    secure: SC1mdfvKoEQC8JT+sHbQ3DhUbGdTKvDZ/lGFEStrupCpKyAnnmMI13pMsVmf7gwDclpWvbrsP/mn0IJficXKQ+BVPJV7/BSnRux77JDR+xBiVR/p/DTegvo5qSajl3HdcfgH+Lr+jdgsexU47GZrdS6mYUTSEl4kOCkFigcnbdDGspkj5RNcOhRysLEB4qyYoeUsKE45mSv+Ai6lBXqzbucfbH2fkYxYtyoJ5UHmMRT/EG4dCNRgg0Ew3tDBvNHUp5JGtZOLu01pIpuzCAxrX8koWMary29xbFmLu3r96QLXzZauqv1kdbFk0GQuVa6a5iYVsvGd3ohRz5sTgbdChVI0PX3IfKQoFA8mUeWFsrfneo2r6l3cBNQ6OTcLzKRRGGSuI9TehePodaiKtdGE1MyMPo+Uv6rcgxr/7h2GjzAdZX2d0KRdhuvafTCO8ySePpO3sh+OCcbZ/gVT9hGCk4cgx3kztyIYnsm1HtxLLEG+uUT6hLqNgLZ2eE6Gn7+cO6DllnflGpj1M1CKVmlcZLRNUxEVf3gDXPEJ2vJOh27cqfyaOU+mETBcQ1MQqOZMNS3Tn1foZdgZX5d70jpj5P0RP5w1O0/iPWU+U6hoTb4VlEhm/uTGdfvQZaZ0OgkA+/JR34HO2WKk7csTkI6s/Zi6R5Ud58SIhO0oZsYUX24=
  skip_cleanup: true
  on:
    all_branches: true
    tags: true    
- provider: releases
  api_key:
    secure: >
      GuZqxcgBOueUOJWg6t5NaCTIssfkptgdAjwyWm/6SaVXqs9Kdgy
      EawtYSu0WLh815qGmuxgVjMbvvkAvtbBXanKH+BheRl1cQjYnza
      XJlL+Oa/xxzCqz1n4txqtDMR7l/loqrMTzCRe2bZ806z3+uXpXh
      CO12+LwvMDJAAddDkX+2wRE240/1f/0lVlZ2lNzgBitC63jAf1H
      ml3/KrgHsTYvNB5M6qKn8C24DcC6PMe012K3hL0O+F+er9Mb39R
      FcSLTjF/6AiLvpK4oDAg8sBgciXVq0FPhCXvjbINGB/AY7jM5Ql
      0A6ngngZjsjefn+NbtZ3aK230h2m0XM+dN7FJCbtRQeqvczcwRT
      /wpDimpzFR0rf/NdXV4G+UZYI6a3bjqKYP5IPN8BbzVo8KzlbGW
      JeJLV40gW7EbdyT57R2dNp46I17c1KL8atQH97n3yv9d9ZaC87O
      6tOohLmue7L3lKxPDpY60VFna5BjJwvrhW4gvsd11Ko4c39FSu8
      ogBSZ6E1EOlmVZDX+cBjuw4dGihcrHqWW5V3k2X/ksAKb+4A74g
      AG8pCr/ifPEj9kTWb71IIF5RHkD6JqeGJdKaWFHDpWlYhKNTLRt
      3gmcgdLmM5MN9A5khwBzPYiF5oaWT1COxh/Rjdz5V0+jUvyRvc9
      a/rvc6hM6quXSmlAwA0U=
  file:
    - pega-kubernetes-example.tar.gz
    - pega-openshift-example.tar.gz
    - pega-azure-aks-example.tar.gz
    - pega-aws-eks-example.tar.gz
    - pega-google-gke-example.tar.gz
    - pega-pivotal-pks-example.tar.gz
  skip_cleanup: true
  on:
    repo: kishorv10/pega-helm-charts
    tags: true
