{{- if .Values.srsStorage.provisionInternalESCluster }}
{{- if or (eq (include "elasticsearch.authProvider" .) "basic-authentication") (eq (include "elasticsearch.authProvider" .) "tls")}}
apiVersion: v1
kind: Secret
metadata:
  name: srs-elastic-credentials
type: kubernetes.io/basic-auth
data:
  username: {{ template "elasticsearchBasicAuthNUsername" . }}
  password: {{ template "elasticsearchBasicAuthNPassword" . }}
{{end}}
{{end}}

{{- if and (not .Values.srsStorage.provisionInternalESCluster) ( .Values.srsStorage.tls) ( .Values.srsStorage.instacluster)}}
apiVersion: v1
kind: Secret
metadata:
  name: srs-elastic-credentials
type: kubernetes.io/basic-auth
data:
  username: {{ template "instaclusterUsername" . }}
  password: {{ template "instaclusterPassword" . }}
{{end}}
