apiVersion: v1
kind: Secret
metadata:
  name: srs-elastic-credentials
type: kubernetes.io/basic-auth
data:
{{- if .Values.srsStorage.provisionInternalESCluster }}
{{- if or (eq (include "elasticsearch.authProvider" .) "basic-authentication") (eq (include "elasticsearch.authProvider" .) "tls")}}
  username: {{ template "elasticsearchBasicAuthNUsername" . }}
  password: {{ template "elasticsearchBasicAuthNPassword" . }}
{{end}}
{{- else if and (not .Values.srsStorage.provisionInternalESCluster) ( .Values.srsStorage.tls.enabled) }}
  username: {{ template "externalESDeploymentUsername" . }}
  password: {{ template "externalESDeploymentPassword" . }}
{{end}}