apiVersion: v1
kind: Secret
metadata:
  name: {{ template "srsRegistrySecret" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imageRepositorySecret" . }}