---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "srs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "srs.srs-service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.srsruntime.replicaCount }}
  selector:
    matchLabels:
{{ include "srs.srs-service.match-labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "srs.srs-service.match-labels" . | indent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.defaultRegistrySecretName }}
      affinity:
{{- include "srs.srs-service.antiaffinity" . | indent 8 }}
      containers:
        - name: srs-service
          image: {{ .Values.imageCredentials.registry }}/{{ .Values.srsruntime.srsImage.name }}:{{ .Values.srsruntime.srsImage.version }}
          imagePullPolicy: {{ .Values.srsruntime.srsImage.pullPolicy }}
          ports:
            - name: srs-port
              containerPort: 8080
              protocol: TCP
            - name: srs-mgmt
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: srs-port
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 30
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ template "elasticsearch.domain" . }}
            - name: ELASTICSEARCH_PORT
              value: {{ template "elasticsearch.port" . }}
            - name: ELASTICSEARCH_PROTO
              value:  {{ template "elasticsearch.protocol" . }}
            - name: APPLICATION_HOST
              value: "0.0.0.0"
            - name: APPLICATION_PORT
              value: "8080"
            - name: AUTH_ENABLED
              value: "{{ .Values.srsruntime.env.AuthEnabled | default "false" }}"
            - name: PUBLIC_KEY_URL
              value: "{{ .Values.srsruntime.env.PublicKeyURL }}"
            - name: MANAGEMENT_PORT
              value: "8081"
          resources:
            {{- toYaml .Values.srsruntime.resources | nindent 12 }}