{{- define "pega.stream.volume" -}}
- name: pega-stream
  mountPath: "/opt/pega/streamvol"
{{- end -}}
{{- define "pega.stream.extraData" -}}
volumeClaimTemplates:
- metadata:
    name: {{ template "pegaStreamName" . }}
    creationTimestamp:
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
serviceName: {{ template "pegaStreamName" . }}
{{- end -}}
{{ if (eq (include "performOnlyDeployment" .) "true") }}
{{ template "pega.deployment" dict "root" $ "node" .Values.stream "name" (include "pegaStreamName" .) "kind" "StatefulSet" "apiVersion" "apps/v1beta2" "nodeType" "Stream" "initContainers" (list "waitForPegaSearch") "extraVolume" "pega.stream.volume" "extraSpecData" "pega.stream.extraData" "custom" .Values.stream.custom }}
{{ end }}
{{ if (eq (include "performInstallAndDeployment" .) "true") }}
{{ template "pega.deployment" dict "root" $ "node" .Values.stream "name" (include "pegaStreamName" .) "kind" "StatefulSet" "apiVersion" "apps/v1beta2" "nodeType" "Stream" "initContainers" (list "waitForPegaDBInstall" "waitForPegaSearch") "extraVolume" "pega.stream.volume" "extraSpecData" "pega.stream.extraData" "custom" .Values.stream.custom }}
{{ end }}
{{ if (eq (include "performUpgradeAndDeployment" .) "true") }}
{{ template "pega.deployment" dict "root" $ "node" .Values.stream "name" (include "pegaStreamName" .) "kind" "StatefulSet" "apiVersion" "apps/v1beta2" "nodeType" "Stream" "initContainers" (list "waitForPegaDBUpgrade") "extraVolume" "pega.stream.volume" "extraSpecData" "pega.stream.extraData" "custom" .Values.stream.custom }}
{{ end }}