kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pegaCredentialsSecret" }}
  namespace: {{ .Release.Namespace }}
data:
  # Base64 encdoded username for connecting to the Pega DB
  DB_USERNAME: {{ .Values.jdbc.username | b64enc }}
  # Base64 encdoded password for connecting to the Pega DB
  DB_PASSWORD: {{ .Values.jdbc.password | b64enc }}

 {{ if (eq (include "performDeployment" .) "true") }}
  # Base64 encdoded username for connecting to cassandra
  CASSANDRA_USERNAME: {{ .Values.dds.username | b64enc }}
  # Base64 encdoded password for connecting to cassandra
  CASSANDRA_PASSWORD: {{ .Values.dds.password | b64enc }}
  # Base64 encdoded username for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_USER: {{ .Values.web.pegaDiagnosticUser | b64enc }}
  # Base64 encdoded password for a Tomcat user that will be created with the PegaDiagnosticUser role
  PEGA_DIAGNOSTIC_PASSWORD: {{ .Values.web.pegaDiagnosticPassword | b64enc }}
{{ end }}
type: Opaque
