global:
  actions:
    execute: ''

srsStorage:
  requireInternetAccess: false
  tls:
    enabled: false
  basicAuthentication:
    enabled: true
  esCredentials:
    username: user
    password: pass