---
# Default values for srs-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true
deploymentName: pega-shared-srs

# srs-service configuration
srsRuntime:
  replicaCount: 2
  # docker image of the srs-service, platform-services/search-n-reporting-service:dockerTag
  srsImage: "YOUR_SRS_IMAGE:TAG"
  # To avoid exposing Docker credentials, optionally create a separate Docker config secret.
  # Specify secret names as an array of comma-separated strings. For example: ["secret1", "secret2"]
  imagePullSecretNames: []
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1300m
      memory: "2Gi"
    requests:
      cpu: 650m
      memory: "2Gi"
  serviceType: "ClusterIP"
  env:
    # AuthEnabled may be set to true when there is an authentication mechanism in place between SRS and Pega Infinity.
    AuthEnabled: false
    # When `AuthEnabled` is `true`, enter the appropriate public key URL. When `AuthEnabled` is `false`(default), leave this parameter empty.
    OAuthPublicKeyURL: ""
