# Default values for srs-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deploymentName: srs
enabled: true
# If using a custom Docker registry, supply the credentials here to pull Docker images.
imageCredentials:
  registry: "YOUR_DOCKER_REGISTRY"
  username: "YOUR_DOCKER_REGISTRY_USERNAME"
  password: "YOUR_DOCKER_REGISTRY_PASSWORD"

srsruntime:
  #srs-service values
  replicaCount: 2
  srsImage:
    name: platform-services/fnx-search
    version: 1.6.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1300m
      memory: "2Gi"
    requests:
      cpu: 650m
      memory: "2Gi"
  serviceType: "ClusterIP"
  env:
    #AuthEnabled may be set to true when there is an authentication mechanism in place between SRS and Pega Infinity.
    AuthEnabled: false
    PublicKeyURL:
