---
# Default values for srs-search.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true
deploymentName: pega-shared-srs

srsRuntime:
  # srs-service values
  replicaCount: 2
  srsImage:
    name: platform-services/fnx-search
    version: 1.7.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1300m
      memory: "2Gi"
    requests:
      cpu: 650m
      memory: "2Gi"
  serviceType: "ClusterIP"
  env:
    # AuthEnabled may be set to true when there is an authentication mechanism in place between SRS and Pega Infinity.
    AuthEnabled: false
    PublicKeyURL:
