{{ if (eq .Values.global.provider "gke") }}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: gke-affinity-session-backendconfig
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 600
{{ end }}