{{ if ((eq (include "deployNonExtStreamSecret" .) "true")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-stream-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{ if .Values.stream.trustStorePassword -}}
  # Base64 encoded password for the stream trust store
  STREAM_TRUSTSTORE_PASSWORD: {{ .Values.stream.trustStorePassword | b64enc }}
    {{- end }}
    {{ if .Values.stream.keyStorePassword -}}
  # Base64 encoded password for the stream key store
  STREAM_KEYSTORE_PASSWORD: {{ .Values.stream.keyStorePassword | b64enc }}
    {{- end }}
    {{ if .Values.stream.jaasConfig -}}
  # Base64 encoded password for the stream trust store
  STREAM_JAAS_CONFIG: {{ .Values.stream.jaasConfig | b64enc }}
    {{- end }}
{{ end }}