{{- if ((eq (include "deployNonExtArtifactorySecret" .) "true")) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "pega-custom-artifactory-secret-name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{ if (eq (include "useBasicAuthForCustomArtifactory" .) "true") }}
  # Base64 encoded username for basic authentication of custom artifactory
  CUSTOM_ARTIFACTORY_USERNAME: {{ .Values.global.customArtifactory.authentication.basic.username | b64enc }}
  # Base64 encoded password for basic authentication of custom artifactory
  CUSTOM_ARTIFACTORY_PASSWORD: {{ .Values.global.customArtifactory.authentication.basic.password | b64enc }}
  {{- end }}

  {{ if (eq (include "useApiKeyForCustomArtifactory" .) "true") }}
  # Base64 encoded dedicated apikey header name and apikey value for authentication of custom artifactory
  CUSTOM_ARTIFACTORY_APIKEY_HEADER: {{ .Values.global.customArtifactory.authentication.apiKey.headerName | b64enc }}
  # Base64 encoded password for basic authentication of custom artifactory
  CUSTOM_ARTIFACTORY_APIKEY: {{ .Values.global.customArtifactory.authentication.apiKey.value | b64enc }}
  {{- end }}
{{ end }}