{{ $depName := printf "%s" (include "deploymentName" $) }}

{{ if (eq (include "performDeployment" $) "true") }}
{{ range $index, $dep := .Values.global.tier }}
{{ if (($dep.service).tls).enabled }}
{{ $data := dict "root" $ "node" $dep "name" $depName }}
{{- include "pegaTomcatKeystoreSecretTemplate" $data }}
{{ end }}
{{ end }}
{{ end }}