{{ if or (eq (include "performInstallAndDeployment" .) "true") (and (eq (include "performOnlyUpgrade" .) "true") (not (eq .Values.upgrade.upgradeType "custom"))) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "installerJobReaderRole" }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
{{ end }}
