{{ if or (eq (include "performInstallAndDeployment" .) "true") (and (eq (include "performOnlyUpgrade" .) "true") (not (eq .Values.upgrade.upgradeType "custom"))) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: check-installer-status
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "installerJobReaderRole" }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{ end }}