{{ if or (eq (include "performInstallAndDeployment" .) "true") (eq (include "performUpgradeAndDeployment" .) "true") (eq (include "isZeroDowntimeUpgrdeInInstaller" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: check-installer-status
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "installerJobReaderRole" }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{ end }}