apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  fluent.conf: |-
    <source>
      @type mounted-file
      path /opt/hazelcast/logs/*.log
      labels app=hazelcast, _container=hazelcast
    </source>

  ## Without this all our log stream names end up unreadable.
    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        stream_name ${record["kubernetes"]["pod_name"]}.${record["kubernetes"]["container_name"]}.${File.basename(record["stream"]).gsub("\.%Y-%m-%d",'')}
      </record>
    </filter>

  ## Will forward all the pod logs to Cloudwatch service logGroup
    <match **>
  # Plugin used for forwarding logs to Cloudwatch
      @type {{ .Values.logForwarder }}
      log_group_name /aws/eks/{{ .Values.ClusterName }}/cluster/namespace/{{ .Release.Namespace }}
    </match>