name: GitHub Actions for pega helm chart

env:
  HELM_URL: https://get.helm.sh
  HELM_TGZ: helm-v3.2.4-linux-amd64.tar.gz
  YAMLLINT_VERSION: 1.15.0
  TRAVIS_GO_VERSION: 1.13.1


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
  #   - cron:  '0 12 * * *'

jobs:
  install-softwares:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Helm
        run: |
          wget -q ${{ env.HELM_URL }}/${{ env.HELM_TGZ }}
          tar xzf ${{ env.HELM_TGZ }}
          PATH=`pwd`/linux-amd64/:$PATH
      - name: Install yamllint
        run: |
          sudo pip install yamllint=="${{ env.YAMLLINT_VERSION }}"
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install npm dependencies
        run: |    
          npm install -g --save remark-cli to-vfile remark-preset-lint-recommended remark-validate-links remark-lint-no-dead-urls remark-message-control remark-preset-lint-markdown-style-guide remark-lint
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.TRAVIS_GO_VERSION }}
      - run: export  PATH=$PATH:/usr/local/go/bin
