name: GitHub Actions Deploy for pega helm chart

env:
  HELM_URL: https://get.helm.sh
  HELM_TGZ: helm-v3.2.4-linux-amd64.tar.gz
  YAMLLINT_VERSION: 1.15.0
  GO_VERSION: 1.13.1


on:
  push:
    branches: [ master ]
    # tags:
    #   - '*'
  pull_request:
    branches: [ master ]
  # schedule:
  #   - cron:  '0 12 * * *'

jobs:
  run-deploy-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Helm
        run: |
          wget -q ${{ env.HELM_URL }}/${{ env.HELM_TGZ }}
          tar xzf ${{ env.HELM_TGZ }}
          ls -l
          mv linux-amd64/helm /usr/local/bin/helm
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Now load the helm dependencies
        run: |
          make dependencies

      - name: before deploy step 1
        run: |
          cd $GITHUB_WORKSPACE
          chmod 777 before_deploy.sh
          ./before_deploy.sh

      - name: before deploy step 2
        run: |
          make examples 

      # - name: deploy on github releases
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     prerelease: false
      #     files: |
      #       pega-kubernetes-example.tar.gz
      #       pega-openshift-example.tar.gz
      #       pega-azure-aks-example.tar.gz
      #       pega-aws-eks-example.tar.gz
      #       pega-google-gke-example.tar.gz
      #       pega-pivotal-pks-example.tar.gz
      #     repo_token: ${{ secrets.NEW_SECRET }}

      - name: deploy on github pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          keep_history: true
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_SECRET }}